In [1]:
# Dependencies
import pandas as pd
import json
import requests
import numpy as np
from pprint import pprint

In [2]:
# Read file and store in DataFrame
Rocket_data  = pd.read_csv("Resources/rockets.csv")

In [3]:
# API url
url = "https://api.spacexdata.com/v3/rockets"

In [4]:
# Retrive API data & print

response = requests.get(url)
response_json = response.json()
print(json.dumps(response_json, indent=4, sort_keys=True))

[
    {
        "active": false,
        "boosters": 0,
        "company": "SpaceX",
        "cost_per_launch": 6700000,
        "country": "Republic of the Marshall Islands",
        "description": "The Falcon 1 was an expendable launch system privately developed and manufactured by SpaceX during 2006-2009. On 28 September 2008, Falcon 1 became the first privately-developed liquid-fuel launch vehicle to go into orbit around the Earth.",
        "diameter": {
            "feet": 5.5,
            "meters": 1.68
        },
        "engines": {
            "engine_loss_max": 0,
            "isp": {
                "sea_level": 267,
                "vacuum": 304
            },
            "layout": "single",
            "number": 1,
            "propellant_1": "liquid oxygen",
            "propellant_2": "RP-1 kerosene",
            "thrust_sea_level": {
                "kN": 420,
                "lbf": 94000
            },
            "thrust_to_weight": 96,
            "thrust_vacuum": {
                "kN": 480,
                "lbf": 110000
            },
            "type": "merlin",
            "version": "1C"
        },
        "first_flight": "2006-03-24",
        "first_stage": {
            "burn_time_sec": 169,
            "engines": 1,
            "fuel_amount_tons": 44.3,
            "reusable": false,
            "thrust_sea_level": {
                "kN": 420,
                "lbf": 94000
            },
            "thrust_vacuum": {
                "kN": 480,
                "lbf": 110000
            }
        },
        "flickr_images": [
            "https://imgur.com/DaCfMsj.jpg",
            "https://imgur.com/azYafd8.jpg"
        ],
        "height": {
            "feet": 73,
            "meters": 22.25
        },
        "id": 1,
        "landing_legs": {
            "material": null,
            "number": 0
        },
        "mass": {
            "kg": 30146,
            "lb": 66460
        },
        "payload_weights": [
            {
                "id": "leo",
                "kg": 450,
                "lb": 992,
                "name": "Low Earth Orbit"
            }
        ],
        "rocket_id": "falcon1",
        "rocket_name": "Falcon 1",
        "rocket_type": "rocket",
        "second_stage": {
            "burn_time_sec": 378,
            "engines": 1,
            "fuel_amount_tons": 3.38,
            "payloads": {
                "composite_fairing": {
                    "diameter": {
                        "feet": 4.9,
                        "meters": 1.5
                    },
                    "height": {
                        "feet": 11.5,
                        "meters": 3.5
                    }
                },
                "option_1": "composite fairing"
            },
            "reusable": false,
            "thrust": {
                "kN": 31,
                "lbf": 7000
            }
        },
        "stages": 2,
        "success_rate_pct": 40,
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_1"
    },
    {
        "active": true,
        "boosters": 0,
        "company": "SpaceX",
        "cost_per_launch": 50000000,
        "country": "United States",
        "description": "Falcon 9 is a two-stage rocket designed and manufactured by SpaceX for the reliable and safe transport of satellites and the Dragon spacecraft into orbit.",
        "diameter": {
            "feet": 12,
            "meters": 3.7
        },
        "engines": {
            "engine_loss_max": 2,
            "isp": {
                "sea_level": 288,
                "vacuum": 312
            },
            "layout": "octaweb",
            "number": 9,
            "propellant_1": "liquid oxygen",
            "propellant_2": "RP-1 kerosene",
            "thrust_sea_level": {
                "kN": 845,
                "lbf": 190000
            },
            "thrust_to_weight": 180.1,
            "thrust_vacuum": {
                "kN": 914,
                "lbf": 205500
            },
            "type": "merlin",
            "version": "1D+"
        },
        "first_flight": "2010-06-04",
        "first_stage": {
            "burn_time_sec": 162,
            "engines": 9,
            "fuel_amount_tons": 385,
            "reusable": true,
            "thrust_sea_level": {
                "kN": 7607,
                "lbf": 1710000
            },
            "thrust_vacuum": {
                "kN": 8227,
                "lbf": 1849500
            }
        },
        "flickr_images": [
            "https://farm1.staticflickr.com/929/28787338307_3453a11a77_b.jpg",
            "https://farm4.staticflickr.com/3955/32915197674_eee74d81bb_b.jpg",
            "https://farm1.staticflickr.com/293/32312415025_6841e30bf1_b.jpg",
            "https://farm1.staticflickr.com/623/23660653516_5b6cb301d1_b.jpg",
            "https://farm6.staticflickr.com/5518/31579784413_d853331601_b.jpg",
            "https://farm1.staticflickr.com/745/32394687645_a9c54a34ef_b.jpg"
        ],
        "height": {
            "feet": 229.6,
            "meters": 70
        },
        "id": 2,
        "landing_legs": {
            "material": "carbon fiber",
            "number": 4
        },
        "mass": {
            "kg": 549054,
            "lb": 1207920
        },
        "payload_weights": [
            {
                "id": "leo",
                "kg": 22800,
                "lb": 50265,
                "name": "Low Earth Orbit"
            },
            {
                "id": "gto",
                "kg": 8300,
                "lb": 18300,
                "name": "Geosynchronous Transfer Orbit"
            },
            {
                "id": "mars",
                "kg": 4020,
                "lb": 8860,
                "name": "Mars Orbit"
            }
        ],
        "rocket_id": "falcon9",
        "rocket_name": "Falcon 9",
        "rocket_type": "rocket",
        "second_stage": {
            "burn_time_sec": 397,
            "engines": 1,
            "fuel_amount_tons": 90,
            "payloads": {
                "composite_fairing": {
                    "diameter": {
                        "feet": 17.1,
                        "meters": 5.2
                    },
                    "height": {
                        "feet": 43,
                        "meters": 13.1
                    }
                },
                "option_1": "dragon",
                "option_2": "composite fairing"
            },
            "reusable": false,
            "thrust": {
                "kN": 934,
                "lbf": 210000
            }
        },
        "stages": 2,
        "success_rate_pct": 97,
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_9"
    },
    {
        "active": true,
        "boosters": 2,
        "company": "SpaceX",
        "cost_per_launch": 90000000,
        "country": "United States",
        "description": "With the ability to lift into orbit over 54 metric tons (119,000 lb)--a mass equivalent to a 737 jetliner loaded with passengers, crew, luggage and fuel--Falcon Heavy can lift more than twice the payload of the next closest operational vehicle, the Delta IV Heavy, at one-third the cost.",
        "diameter": {
            "feet": 39.9,
            "meters": 12.2
        },
        "engines": {
            "engine_loss_max": 6,
            "isp": {
                "sea_level": 288,
                "vacuum": 312
            },
            "layout": "octaweb",
            "number": 27,
            "propellant_1": "liquid oxygen",
            "propellant_2": "RP-1 kerosene",
            "thrust_sea_level": {
                "kN": 845,
                "lbf": 190000
            },
            "thrust_to_weight": 180.1,
            "thrust_vacuum": {
                "kN": 914,
                "lbf": 205500
            },
            "type": "merlin",
            "version": "1D+"
        },
        "first_flight": "2018-02-06",
        "first_stage": {
            "burn_time_sec": 162,
            "cores": 3,
            "engines": 27,
            "fuel_amount_tons": 1155,
            "reusable": true,
            "thrust_sea_level": {
                "kN": 22819,
                "lbf": 5130000
            },
            "thrust_vacuum": {
                "kN": 24681,
                "lbf": 5548500
            }
        },
        "flickr_images": [
            "https://farm5.staticflickr.com/4599/38583829295_581f34dd84_b.jpg",
            "https://farm5.staticflickr.com/4645/38583830575_3f0f7215e6_b.jpg",
            "https://farm5.staticflickr.com/4696/40126460511_b15bf84c85_b.jpg",
            "https://farm5.staticflickr.com/4711/40126461411_aabc643fd8_b.jpg"
        ],
        "height": {
            "feet": 229.6,
            "meters": 70
        },
        "id": 3,
        "landing_legs": {
            "material": "carbon fiber",
            "number": 12
        },
        "mass": {
            "kg": 1420788,
            "lb": 3125735
        },
        "payload_weights": [
            {
                "id": "leo",
                "kg": 63800,
                "lb": 140660,
                "name": "Low Earth Orbit"
            },
            {
                "id": "gto",
                "kg": 26700,
                "lb": 58860,
                "name": "Geosynchronous Transfer Orbit"
            },
            {
                "id": "mars",
                "kg": 16800,
                "lb": 37040,
                "name": "Mars Orbit"
            },
            {
                "id": "pluto",
                "kg": 3500,
                "lb": 7720,
                "name": "Pluto Orbit"
            }
        ],
        "rocket_id": "falconheavy",
        "rocket_name": "Falcon Heavy",
        "rocket_type": "rocket",
        "second_stage": {
            "burn_time_sec": 397,
            "engines": 1,
            "fuel_amount_tons": 90,
            "payloads": {
                "composite_fairing": {
                    "diameter": {
                        "feet": 17.1,
                        "meters": 5.2
                    },
                    "height": {
                        "feet": 43,
                        "meters": 13.1
                    }
                },
                "option_1": "dragon",
                "option_2": "composite fairing"
            },
            "reusable": false,
            "thrust": {
                "kN": 934,
                "lbf": 210000
            }
        },
        "stages": 2,
        "success_rate_pct": 100,
        "wikipedia": "https://en.wikipedia.org/wiki/Falcon_Heavy"
    },
    {
        "active": false,
        "boosters": 0,
        "company": "SpaceX",
        "cost_per_launch": 7000000,
        "country": "United States",
        "description": "Starship and Super Heavy Rocket represent a fully reusable transportation system designed to service all Earth orbit needs as well as the Moon and Mars. This two-stage vehicle \u2014 composed of the Super Heavy rocket (booster) and Starship (ship) \u2014 will eventually replace Falcon 9, Falcon Heavy and Dragon.",
        "diameter": {
            "feet": 30,
            "meters": 9
        },
        "engines": {
            "engine_loss_max": null,
            "isp": {
                "sea_level": 330,
                "vacuum": 380
            },
            "layout": null,
            "number": 37,
            "propellant_1": "liquid oxygen",
            "propellant_2": "liquid methane",
            "thrust_sea_level": {
                "kN": 1780,
                "lbf": 400000
            },
            "thrust_to_weight": 107,
            "thrust_vacuum": {
                "kN": 1960,
                "lbf": 440000
            },
            "type": "raptor",
            "version": ""
        },
        "first_flight": "2021-12-01",
        "first_stage": {
            "burn_time_sec": null,
            "engines": 37,
            "fuel_amount_tons": 3300,
            "reusable": true,
            "thrust_sea_level": {
                "kN": 128000,
                "lbf": 28775544
            },
            "thrust_vacuum": {
                "kN": 138000,
                "lbf": 31023634
            }
        },
        "flickr_images": [
            "https://live.staticflickr.com/65535/48954138962_ee541e6755_b.jpg",
            "https://live.staticflickr.com/65535/48953946911_e60c5bcc5c_b.jpg",
            "https://live.staticflickr.com/65535/48954138922_9c42173f08_b.jpg",
            "https://live.staticflickr.com/65535/48953947006_313f01ec93_b.jpg"
        ],
        "height": {
            "feet": 387,
            "meters": 118
        },
        "id": 4,
        "landing_legs": {
            "material": "stainless steel",
            "number": 6
        },
        "mass": {
            "kg": 1335000,
            "lb": 2943000
        },
        "payload_weights": [
            {
                "id": "leo",
                "kg": 150000,
                "lb": 330000,
                "name": "Low Earth Orbit"
            },
            {
                "id": "mars",
                "kg": 100000,
                "lb": 220000,
                "name": "Mars Orbit"
            },
            {
                "id": "moon",
                "kg": 100000,
                "lb": 220000,
                "name": "Moon Orbit"
            }
        ],
        "rocket_id": "starship",
        "rocket_name": "Starship",
        "rocket_type": "rocket",
        "second_stage": {
            "burn_time_sec": null,
            "engines": 6,
            "fuel_amount_tons": 1200,
            "payloads": {
                "composite_fairing": {
                    "diameter": {
                        "feet": null,
                        "meters": null
                    },
                    "height": {
                        "feet": null,
                        "meters": null
                    }
                },
                "option_1": "Spaceship",
                "option_2": "composite fairing"
            },
            "reusable": true,
            "thrust": {
                "kN": 1957,
                "lbf": 440000
            }
        },
        "stages": 2,
        "success_rate_pct": 0,
        "wikipedia": "https://en.wikipedia.org/wiki/SpaceX_Starship"
    }
]

In [5]:
# Create two columns in DF
Rocket_data['id'] =''
Rocket_data['success_rate'] =''

# Read data from API and add to DF 
for index,row in Rocket_data.iterrows():
    for result in response_json:
        if result["rocket_name"] == row["name"]:
            Rocket_data.loc[index,"id"] = result["rocket_id"]
            Rocket_data.loc[index,"success_rate"] = result["success_rate_pct"]

# Display DF
Rocket_data

,rocket_id,name,type,active,country,company,height_mt,height_ft,diameter_mt,diameter_ft,mass_kg,mass_lb,stages,boosters,cost_per_launch,landing_legs,engines,id,success_rate
0,5e9d0d95eda69955f709d1eb,Falcon 1,rocket,False,Republic of the Marshall Islands,SpaceX,22.25,73.0,1.68,5.5,30146,66460,2,0,6700000,"{'number': 0, 'material': None}","{'isp': {'sea_level': 267, 'vacuum': 304}, 'th...",falcon1,40
1,5e9d0d95eda69973a809d1ec,Falcon 9,rocket,True,United States,SpaceX,70.00,229.6,3.70,12.0,549054,1207920,2,0,50000000,"{'number': 4, 'material': 'carbon fiber'}","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...",falcon9,97
2,5e9d0d95eda69974db09d1ed,Falcon Heavy,rocket,True,United States,SpaceX,70.00,229.6,12.20,39.9,1420788,3125735,2,2,90000000,"{'number': 12, 'material': 'carbon fiber'}","{'isp': {'sea_level': 288, 'vacuum': 312}, 'th...",falconheavy,100
3,5e9d0d96eda699382d09d1ee,Starship,rocket,False,United States,SpaceX,118.00,387.0,9.00,30.0,1335000,2943000,2,0,7000000,"{'number': 6, 'material': 'stainless steel'}","{'isp': {'sea_level': 330, 'vacuum': 380}, 'th...",starship,0

In [6]:
# Rearrange and rename the columns 
Rocket_data_Final = Rocket_data[["id", "name", "type", "active", "country", "company", "height_ft", "diameter_ft", "mass_lb",
                                 "stages","boosters", "cost_per_launch", "success_rate"]]

Rocket_data_Final = Rocket_data_Final.rename(columns={"id": "rocket_id" })

# Display Final DF
Rocket_data_Final

,rocket_id,name,type,active,country,company,height_ft,diameter_ft,mass_lb,stages,boosters,cost_per_launch,success_rate
0,falcon1,Falcon 1,rocket,False,Republic of the Marshall Islands,SpaceX,73.0,5.5,66460,2,0,6700000,40
1,falcon9,Falcon 9,rocket,True,United States,SpaceX,229.6,12.0,1207920,2,0,50000000,97
2,falconheavy,Falcon Heavy,rocket,True,United States,SpaceX,229.6,39.9,3125735,2,2,90000000,100
3,starship,Starship,rocket,False,United States,SpaceX,387.0,30.0,2943000,2,0,7000000,0

In [7]:
# Write DF to CSV
Rocket_data_Final.to_csv ("Clean_csv/rockets.csv", index = False, header=True)